### ISSUE TITLE
Does this software work in a Ubuntu 18.04 machine without GPU?

### ISSUE THREAD

**Issue by PauloMendes33** [UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp#9]
Hello @UNeedCryDear 

I am writing to know if your software was tested in a Ubuntu 18.04 machine without GPU.
I am testing it and the onnxruntime software is returning errors, my problem for sure, just wanted to know if it was already tested in a Ubuntu 18.04 machine withou any GPU?
 

Best Regards.
Paulo Mendes

**Comment by UNeedCryDear** [comment]
No. And can you show me the error message?
I have an Ubuntu, but it is only used to run neural-network. If your error message is not obvious, I will test it on Ubuntu(22.04 LTS) later.

**Comment by PauloMendes33** [comment]
Hello @UNeedCryDear 

I have seen your software and I wanted to know, is it supposed to work in a machine without GPU?
In the future I will test it in a Nvidia AGX Xavier with Ubuntu 20.04, and I will tell you my conclusions.

The error returned is a onnxruntime error, not from your software, and it is the following:
(I am using Ubuntu 18.04 with NetBeans 8.1 in a Machine without GPU --- I intend to make the processing using the CPU)
error message -> build/Debug/GNU-Linux/main.o: In function `__static_initialization_and_destruction_0(int, int)':
/home/$USER/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h:114: undefined reference to `OrtGetApiBase'

I had to manually install cmake 3.26 and after I manually installed onnxruntime following the steps in the official link (https://onnxruntime.ai/docs/build/inferencing.html)

I will study this and try to surrpass the error.

Best Regards.
Paulo Mendes

**Comment by UNeedCryDear** [comment]
According to your information, I think this is the problem of onnxruntime. I haven't built onnxruntime on Linux, so you have to see for yourself whether there is a solution:
https://github.com/microsoft/onnxruntime/issues?q=is%3Aissue+undefined+reference+to+OrtGetApiBase+is%3Aclosed

**Comment by PauloMendes33** [comment]
Hello @UNeedCryDear 

I think I have surpassed the error.
What I did was to add the libonnxruntime.so in the onnxruntime installation folder to the project created in NetBeans in the libraries in the Build->Linker. Also, I changed the include in the header files of the header onnxruntime_cxx_api.h from -> //#include <onnxruntime_cxx_api.h>
#include </home/#USER/onnxruntime/include/onnxruntime/core/session/onnxruntime_cxx_api.h>

Now I have another error in your software, in the yolov5_seg_onnx.cpp and it is as follows:
/home/#USER/NetBeansProjects/YOLOv5_inst_seg_Intel_RSD455/yolov5_seg_onnx.cpp:29: undefined reference to `OrtSessionOptionsAppendExecutionProvider_CUDA'

After this error I added all libonnxruntime##.so to the libraries in the NetBeans project. The error continues. I have onnxruntime 1.15.0

Looked for the error in the internet and nothing. I think it could be that OrtSessionOptionsAppendExecutionProvider_CUDA is no longer used with this name in the onnxruntime version 1.15.0.

I don't know. I will continue working on this.

Best Regards.
Paulo Mendes

**Comment by PauloMendes33** [comment]
Hello @UNeedCryDear 

I have commented the code line //OrtStatus* status = OrtSessionOptionsAppendExecutionProvider_CUDA(_OrtSessionOptions, cudaID);
		in the yolov5_seg_onnx.cpp since I don't want to use the GPU in my machine.

The error was surpassed and the software compiles well.

Now.

In the main.cpp i changed the code to:
if (test.ReadModel(net, model_path, false)) {
		cout << "read net ok!" << endl;
	}
	else {
            cout << "error reading net pm33" << endl;
		return -1;
	}

The error output I obtain is:
[ERROR:0] global /home/pauloasmendes/opencv-4.5.4/modules/dnn/src/onnx/onnx_importer.cpp (720) handleNode DNN/ONNX: ERROR during processing node with 3 inputs and 1 outputs: [Range]:(/model.24/Range_output_0)
error reading net pm33
Your ORT build without GPU. Change to CPU.
A************* Infer model on CPU! *************

RUN FINISHED; exit value 0; real time: 160ms; user: 80ms; system: 110ms


I changed the main.cpp to
test.ReadModel(net, model_path, false)   so it makes processing using CPU, but it doesn't load the model. I even tried with the official yolov5s-seg.onnx converted from the yolov5s-seg.pt.

What could be the problem?  I am using OpenCV version 4.5.4

Best Regards.
Paulo Mendes

**Comment by UNeedCryDear** [comment]
[```(test.ReadModel(net, model_path, false)```,](https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/blob/d9ce33c26631ff6cdfbb905420bec998388e472d/main.cpp#L18) 
This interface is for opencv, not onnxruntime，and the following is the interface for onnxruntime.
https://github.com/UNeedCryDear/yolov5-seg-opencv-onnxruntime-cpp/blob/d9ce33c26631ff6cdfbb905420bec998388e472d/main.cpp#L51
![image](https://user-images.githubusercontent.com/52729998/217603354-50d934e1-bf39-4111-9ef6-7ed883a8829a.png)

At the same time, opencv does not support dynamic model,but onnxruntime supports.
## for oprncv
> python export.py --weights yolov5s-seg.pt --img [640,640] --include onnx --opset 12
## for onnxruntime
> python export.py --weights yolov5s-seg.pt --img [640,640] --include onnx  #static
> python export.py --weights yolov5s-seg.pt  --batch-size bs-number --dynamic --include onnx  #dyamic

**Comment by PauloMendes33** [comment]
Hello @UNeedCryDear 

It worked great with OpenCV and also with onnxruntime, tested both.
For OpenCV used $python export.py --weights yolov5s-seg.pt --img 640 --include onnx --opset 12
For onnx used $python export.py --weights yolov5s-seg.pt --batch-size bs-number --dynamic --include onnx #dyamic

It works great, Your work is awesome, you're the man.
[Ubuntu 18.04+no GPU+NetBeans 8.1+Opencv 4.5.4]
Next I will test it on Nvidia Jetson AGX Xavier with GPU.

Thank you very much for your work.
Best Regards.
Paulo Mendes
